insert into ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('BARQUISIMETO', 'B1', '1K');
insert into ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('BUENOS AIRES', 'B2', '1K');
insert into ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('LIMA', 'l1', '1K');
insert into ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('BOGOTA', 'B3', '1K');

INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('SAAVEDRA',
'JUAN', 'JDSAAVEDRAV@GMAIL.COM', 'VENEZUELA', 'LUIS BELAUSTEGUI', 'CABA', '1125340311');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('TOVAR',
 'SAMUEL', 'TOVAR_SAMUEL@GMAIL.COM', 'VENEZUELA', 'COBO', 'CABA', '1123456790');
 INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('RODRIGUEZ',
 'EMMA', 'EMMA_RS@GMAIL.COM', 'ARGENTINA', 'RIO DE JANEIRO', 'CABA', '1126340606');


